---
- name: Install HAproxy
  package:
    name: "haproxy"
    state: "present"

- name: Enable haproxy service
  replace:
    dest: "/etc/default/haproxy"
    regexp: "ENABLED=0"
    replace: "ENABLED=1"
    backup: "no"
  when: ansible_distribution == 'Ubuntu'

- name: Setup the haproxy configuration file
  copy:
    src: "templates/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
  when: ansible_distribution == 'Ubuntu'

- name: Setup the haproxy configuration file
  copy:
    src: "templates/haproxy_fedora.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
  when: ansible_distribution == 'Fedora'

- name: Add web servers to haproxy
  lineinfile:
    dest: "/etc/haproxy/haproxy.cfg"
    line: "    server ws{{ item[0].openstack[item[1]] }} {{ item[0].openstack[item[1]] }}:80 check"
  with_nested:
    - "{{ hostvars.cloud.webserver.results }}"
    - ["private_v4", "public_v4"]
  when: item[0].openstack[item[1]] != ''
  no_log: True

- name: Ensure HAproxy is restarted
  service:
    name: "haproxy"
    state: "restarted"
    enabled: "yes"
