---
- name: Wait until server is up and runnning
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
  become: no

- name: Install python-dnf when using Fedora
  raw: dnf install -y python-dnf
  when: ansible_distribution == 'Fedora'

- name: Ensure python dependencies are installed on RHEL derivatives
  package:
    name: "{{ item }}"
  with_items:
    - python2
    - libselinux-python
  when: ansible_os_family == 'RedHat'

- name: Set SELinux to permisive
  selinux:
    policy: "targeted"
    state: "permissive"
  when: ansible_os_family == 'RedHat'
