---
- name: Remove floating IP on database server
  os_floating_ip:
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    state: absent
    floating_ip_address: "{{ database.openstack.public_v4 }}"
    server: "{{ database.openstack.name }}"
  when: database.openstack.private_v4 != ""
  no_log: True

- name: Remove floating IP on web server
  os_floating_ip:
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    state: absent
    floating_ip_address: "{{ item.openstack.public_v4 }}"
    server: "{{ item.openstack.name }}"
  with_items: "{{ webserver.results }}"
  when: item.openstack.private_v4 != ""
  no_log: True
