---
- os_floating_ip:
    auth: "{{ auth }}"
    state: absent
    floating_ip_address: "{{ database.openstack.public_v4 }}"
    server: "{{ database.openstack.name }}"
  when: database.openstack.private_v4 != ""

- os_floating_ip:
    auth: "{{ auth }}"
    state: absent
    floating_ip_address: "{{ item.openstack.public_v4 }}"
    server: "{{ item.openstack.name }}"
  with_items: "{{ webserver.results }}"
  when: item.openstack.private_v4 != ""
