---
- debug:
    msg: >-
      export DOCKER_HOST=tcp://{{ hostvars.swarmnode1.swarmnode.openstack.public_v4 }}:2375;
      export DOCKER_TLS_VERIFY=1;
      export DOCKER_CERT_PATH=/tmp/{{ env }}/keys

- debug:
    msg: Start time {{ starttime.time }}, end time {{ ansible_date_time.time }}