---
- name: Get start timestamp
  set_fact: starttime="{{ ansible_date_time }}"

- name: Delete key pairs
  os_keypair:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: "lampstack"
    public_key_file: "{{ app_env.public_key_file }}"

- name: Delete database node
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: database
    image: "{{ app_env.image_name }}"
    key_name: "lampstack"
    timeout: 200
    network: "{{ app_env.private_net_name }}"
    meta:
      hostname: database

- name: Delete balancer node
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: balancer
    image: "{{ app_env.image_name }}"
    key_name: "lampstack"
    timeout: 200
    network: "{{ app_env.private_net_name }}"
    meta:
      hostname: balancer

- name: Delete web server nodes
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: apache-{{ item }}
    image: "{{ app_env.image_name }}"
    key_name: "lampstack"
    timeout: 200
    network: "{{ app_env.private_net_name }}"
    meta:
      hostname: apache-{{ item }}
  with_sequence: count={{ app_env.stack_size - 2 }}

- name: Delete security group
  os_security_group:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: lampstack_sg
    description: secuirty group for lampstack

- name: Delete cinder volume
  os_volume:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    wait: yes
    display_name: db_volume
