---
horizon_url: "https://salesdemo-sjc.openstack.blueboxgrid.com"

auth: {
  auth_url: "https://salesdemo-sjc.openstack.blueboxgrid.com:5000/v2.0",
  username: "litong01",
  password: "{{ password }}",
  project_name: "Interop"
}

app_env: {
  ssh_user: "ubuntu",
  image_name: "ubuntu-15.04",
  region_name: "",
  private_net_name: "interopnet",
  public_net_name: "external",
  flavor_name: "m1.small",
  public_key_file: "/home/tong/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 10,
  block_device_name: "/dev/vdb",
  wp_theme: "https://downloads.wordpress.org/theme/iribbon.2.0.65.zip",
  wp_posts: "http://wpcandy.s3.amazonaws.com/resources/postsxml.zip"
}
